name: Publish Packages

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        registry-url: https://registry.npmjs.org/

    - name: Install dependencies
      run: npm ci

    - name: Publish Packages
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
